# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - performance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://projects.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4783997dbbb74c61b6e4a323fc2848ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0b8ff7fc8b8249879b7ec361860d18e9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: projects.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4783997dbbb74c61b6e4a323fc2848ca }}/projects/studenperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'performance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c64fa2ea4954d48a82004e5f59e0b8f }}
        images: 'projects.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4783997dbbb74c61b6e4a323fc2848ca }}/projects/studenperformance:${{ github.sha }}'